version: '3.8'
services:
  db:
    image: postgres:13.3
    container_name: servicer-db
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: "servicer"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"